### ISSUE TITLE
User defined locale ignored during installation

### ISSUE THREAD

**Issue by jav-mc** [Sylius/Sylius-Standard#169]
When using `composer create-project -s beta sylius/standard` it asks for a locale, with the default being `en_US`, but if you define `en_GB` it gets ignored and installs `en_US` as default locale. Is there a way of preventing this other that going to `app/config/config.yml`, editing the local and running `bin/console sylius:install` again? It's quite annoying and frustrating.

**Comment by lchrusciel** [comment]
It is something related with Sylius/Sylius. Probably the command just is improved and it something we should definitely consider. Can you open this issue on the main repository?

**Comment by ADmad** [comment]
@lchrusciel Nope, the issue is due to `app/config/config.yml` file of this package. The problem is fixed if you remove the following lines:

```yml
parameters:
  locale: en_US
```

In general the `config.yml` (and any other config file if required) need to be updated as per latest config files of `Sylius/Sylius`.

**Comment by lchrusciel** [comment]
I'm not sure what was a reason for adding it in the first place in https://github.com/Sylius/Sylius-Standard/pull/156 /cc @pamil

**Comment by pamil** [comment]
@lchrusciel https://github.com/symfony/symfony-standard/blob/3.3/app/config/config.yml#L6-L9

**Comment by pamil** [comment]
Should be already fixed.

**Comment by pogorivan** [comment]
This issue still exist - can't select default locale during "bin/console sylius:install" - only selecting the currency. So i need to edit locale in config file
